import { AppDatabase } from './types';

export const seedData: AppDatabase = {
  "expenses": [
    {
      "id": "exp-1",
      "requestDate": "2026-03-20",
      "actualDate": "2026-03-20",
      "content": "Chi phí thuê xe ô tô chở Thoa đi từ CT-ĐH xuống dự án HCM-TL-MT",
      "expenseGroup": "Quản lý DN/Công trình (642,627)",
      "expenseType": "Vận chuyển",
      "advanceAmount": 1000000,
      "actualAmount": 1000000,
      "limitType": "0",
      "clearanceStatus": "Xong",
      "documentStatus": "Đầy đủ",
      "missingDocuments": "",
      "invoiceNo": "",
      "notes": "Đã hoàn ứng",
      "createdByRole": "Kế toán dự án",
      "createdAt": "2026-03-20T08:00:00.000Z"
    },
    {
      "id": "exp-2",
      "requestDate": "2026-03-21",
      "actualDate": "2026-03-21",
      "content": "Thuê phòng thanh toán đến ngày 21/03",
      "expenseGroup": "Quản lý DN/Công trình (642,627)",
      "expenseType": "Công tác phí",
      "advanceAmount": 0,
      "actualAmount": 3525000,
      "limitType": "Theo thực tế",
      "clearanceStatus": "Đang hoàn ứng",
      "documentStatus": "Thiếu chứng từ",
      "missingDocuments": "Chưa nộp hóa đơn phòng nghỉ",
      "invoiceNo": "",
      "notes": "Quá hạn 57 ngày",
      "createdByRole": "Kế toán dự án",
      "createdAt": "2026-03-21T08:30:00.000Z"
    },
    {
      "id": "exp-3",
      "requestDate": "2026-03-21",
      "actualDate": "2026-03-21",
      "content": "Mua xe máy 2 chiếc phục vụ hiện trường",
      "expenseGroup": "Quản lý DN/Công trình (642,627)",
      "expenseType": "Hành chính",
      "advanceAmount": 20000000,
      "actualAmount": 20000000,
      "limitType": "0",
      "clearanceStatus": "Đang hoàn ứng",
      "documentStatus": "Thiếu chứng từ",
      "missingDocuments": "Hóa đơn VAT và giấy đăng ký xe",
      "invoiceNo": "",
      "notes": "Quá hạn 57 ngày",
      "createdByRole": "Kế toán dự án",
      "createdAt": "2026-03-21T09:00:00.000Z",
      "dossierCode": "HS-XE-01"
    },
    {
      "id": "exp-4",
      "requestDate": "2026-03-21",
      "actualDate": "2026-03-21",
      "content": "Thanh toán tiền cơm của Trần Khắc Trung và A Kiên tại hiện bãi",
      "expenseGroup": "Quản lý DN/Công trình (642,627)",
      "expenseType": "Bếp ăn",
      "advanceAmount": 1680000,
      "actualAmount": 1680000,
      "limitType": "60k/người",
      "clearanceStatus": "Đang hoàn ứng",
      "documentStatus": "Đầy đủ",
      "missingDocuments": "",
      "invoiceNo": "",
      "notes": "Bếp ăn công trình/Ăn ngoài (627)",
      "createdByRole": "Hành chính nhân sự (HCNS)",
      "createdAt": "2026-03-21T10:00:00.000Z",
      "dossierCode": "HS-XE-01"
    },
    {
      "id": "exp-5",
      "requestDate": "2026-03-21",
      "actualDate": "2026-03-21",
      "content": "Thanh toán chi phí mua 100 lít dầu Do 0.05S-II",
      "expenseGroup": "Chi phí thi công (621,622,623)",
      "expenseType": "Dầu (621)",
      "advanceAmount": 3342000,
      "actualAmount": 3342000,
      "limitType": "Theo định mức",
      "clearanceStatus": "Xong",
      "documentStatus": "Đầy đủ",
      "missingDocuments": "",
      "invoiceNo": "18109 vs 18110",
      "notes": "Dầu (621) - Đã nhập kho dầu",
      "createdByRole": "Thủ kho",
      "createdAt": "2026-03-21T11:00:00.000Z"
    },
    {
      "id": "exp-6",
      "requestDate": "2026-03-25",
      "actualDate": "2026-03-25",
      "content": "Thanh toán tiền xăng 51M97730 Fortuner chở sếp Tuấn về SG",
      "expenseGroup": "Chi phí thi công (621,622,623)",
      "expenseType": "Dầu (621)",
      "advanceAmount": 500000,
      "actualAmount": 500000,
      "limitType": "Theo định mức",
      "clearanceStatus": "Xong",
      "documentStatus": "Đầy đủ",
      "missingDocuments": "",
      "invoiceNo": "637268",
      "notes": "Đã hoàn ứng",
      "createdByRole": "Kế toán dự án",
      "createdAt": "2026-03-25T08:00:00.000Z"
    },
    {
      "id": "exp-7",
      "requestDate": "2026-03-26",
      "actualDate": "2026-03-26",
      "content": "Thanh toán tiền mua 50 lít dầu cấp máy đào 07 làm mặt bằng bãi dầm",
      "expenseGroup": "Chi phí thi công (621,622,623)",
      "expenseType": "Dầu (621)",
      "advanceAmount": 1000200,
      "actualAmount": 1000200,
      "limitType": "Theo định mức",
      "clearanceStatus": "Đang hoàn ứng",
      "documentStatus": "Thiếu chứng từ",
      "missingDocuments": "Thiếu hóa đơn lẻ",
      "invoiceNo": "19658",
      "notes": "Hạch toán lệch 55,700đ",
      "createdByRole": "Kế toán dự án",
      "createdAt": "2026-03-26T08:30:00.000Z"
    },
    {
      "id": "exp-8",
      "requestDate": "2026-03-26",
      "actualDate": "2026-03-26",
      "content": "Thanh toán tiền đổ xăng xe Fotuner để sếp Thạch về SG",
      "expenseGroup": "Chi phí thi công (621,622,623)",
      "expenseType": "Dầu (621)",
      "advanceAmount": 950000,
      "actualAmount": 950000,
      "limitType": "Theo định mức",
      "clearanceStatus": "Đang hoàn ứng",
      "documentStatus": "Thiếu chứng từ",
      "missingDocuments": "Thiếu hóa đơn gốc",
      "invoiceNo": "19659",
      "notes": "Được duyệt tạm ứng",
      "createdByRole": "Kế toán dự án",
      "createdAt": "2026-03-26T09:00:00.000Z"
    },
    {
      "id": "exp-9",
      "requestDate": "2026-04-01",
      "actualDate": "2026-04-01",
      "content": "Chi phí thuê xe Lalamove chuyển máy lạnh và đồ xuống văn phòng dự án",
      "expenseGroup": "Quản lý DN/Công trình (642,627)",
      "expenseType": "Vận chuyển",
      "advanceAmount": 1200000,
      "actualAmount": 1200000,
      "limitType": "0",
      "clearanceStatus": "Xong",
      "documentStatus": "Đầy đủ",
      "missingDocuments": "",
      "invoiceNo": "LLM-29938",
      "notes": "Chuyển máy lạnh văn phòng BĐH",
      "createdByRole": "Hành chính nhân sự (HCNS)",
      "createdAt": "2026-04-01T10:00:00.000Z"
    },
    {
      "id": "exp-10",
      "requestDate": "2026-04-04",
      "actualDate": "2026-04-04",
      "content": "Thanh toán tiền mua dầu cấp 50 lít cho máy đào 09 thi công bãi đúc dầm",
      "expenseGroup": "Chi phí thi công (621,622,623)",
      "expenseType": "Dầu (621)",
      "advanceAmount": 2239000,
      "actualAmount": 2239000,
      "limitType": "Theo định mức",
      "clearanceStatus": "Xong",
      "documentStatus": "Đầy đủ",
      "missingDocuments": "",
      "invoiceNo": "31969",
      "notes": "Đã chi và hoàn ứng",
      "createdByRole": "Thủ kho",
      "createdAt": "2026-04-04T08:00:00.000Z"
    }
  ],
  "funds": [
    {
      "id": "f-1",
      "date": "2026-03-21",
      "content": "Số tiền tạm ứng ban đầu cấp cho quỹ HCNS từ Công ty",
      "amount": 76270000,
      "source": "Ngân sách",
      "notes": "Nhập ban đầu cho hoạt động văn phòng",
      "fundType": "HCNS",
      "createdAt": "2026-03-21T07:00:00.000Z"
    },
    {
      "id": "f-2",
      "date": "2026-03-25",
      "content": "Nhập quỹ mua dầu từ công ty đợt 1",
      "amount": 40896000,
      "source": "Ngân sách",
      "notes": "Phục vụ nhiên liệu thi công máy công trình",
      "fundType": "Dầu",
      "createdAt": "2026-03-25T07:15:00.000Z"
    },
    {
      "id": "f-3",
      "date": "2026-04-03",
      "content": "Mượn quỹ BĐH từ sếp Thạch đổ dầu khẩn cấp",
      "amount": 10000000,
      "source": "Mượn sếp",
      "notes": "Sếp Thạch cấp mượn trực tiếp",
      "fundType": "Dầu",
      "createdAt": "2026-04-03T09:00:00.000Z"
    },
    {
      "id": "f-4",
      "date": "2026-04-05",
      "content": "Mượn quỹ BĐH từ sếp Thạch mua dầu và vật tư khẩn cấp đợt 2",
      "amount": 10000000,
      "source": "Mượn sếp",
      "notes": "Cấp tiền mặt",
      "fundType": "Dầu",
      "createdAt": "2026-04-05T09:30:00.000Z"
    },
    {
      "id": "f-5",
      "date": "2026-04-06",
      "content": "Nhập quỹ mua dầu từ công ty đợt 2",
      "amount": 50000000,
      "source": "Ngân sách",
      "notes": "Chuyển khoản công ty cấp quỹ",
      "fundType": "Dầu",
      "createdAt": "2026-04-06T08:00:00.000Z"
    },
    {
      "id": "f-6",
      "date": "2026-04-08",
      "content": "Tạm ứng đợt 2 cho quỹ hành chính nhân sự HCNS",
      "amount": 30000000,
      "source": "Ngân sách",
      "notes": "Nhập quỹ văn phòng",
      "fundType": "HCNS",
      "createdAt": "2026-04-08T08:00:00.000Z"
    },
    {
      "id": "f-7",
      "date": "2026-04-14",
      "content": "Nhập quỹ mua dầu từ công ty đợt 3",
      "amount": 39184000,
      "source": "Ngân sách",
      "notes": "Dầu phục vụ đổ máy đào 07 & 09",
      "fundType": "Dầu",
      "createdAt": "2026-04-14T08:00:00.000Z"
    },
    {
      "id": "f-8",
      "date": "2026-04-20",
      "content": "Tạm ứng quỹ HCNS đợt 3",
      "amount": 66000000,
      "source": "Ngân sách",
      "notes": "Bếp ăn và sinh hoạt",
      "fundType": "HCNS",
      "createdAt": "2026-04-20T08:00:00.000Z"
    },
    {
      "id": "f-9",
      "date": "2026-04-29",
      "content": "Tạm ứng hành chính đợt 4 (Quỹ HCNS)",
      "amount": 30000000,
      "source": "Ngân sách",
      "notes": "Hạch toán đợt cuối tháng 4",
      "fundType": "HCNS",
      "createdAt": "2026-04-29T10:00:00.000Z"
    }
  ],
  "documents": [
    {
      "id": "doc-1",
      "code": "HD-001",
      "name": "Hợp đồng thuê xe ô tô đưa đón chỉ huy dự án",
      "expenseId": "exp-1",
      "category": "Hợp đồng",
      "status": "Lưu trữ",
      "updatedAt": "2026-06-01",
      "assignedTo": "Hành chính nhân sự (HCNS)",
      "notes": "Ký kết cùng nhà xe Thắng Lợi"
    },
    {
      "id": "doc-2",
      "code": "HDD-18109",
      "name": "Biên bản nghiệm thu cấp dầu đợt 1 - HĐ 18109",
      "expenseId": "exp-5",
      "category": "Biên bản bàn giao" as any, // fallback for schema type compatibility
      "status": "Hoàn tất",
      "updatedAt": "2026-06-01",
      "assignedTo": "Thủ kho",
      "notes": "Thủ kho lưu hồ sơ giấy tại văn phòng"
    },
    {
      "id": "doc-3",
      "code": "VAT-3525",
      "name": "Yêu cầu xuất hóa đơn đỏ chi phí thuê phòng tới 21/03",
      "expenseId": "exp-2",
      "category": "Hóa đơn",
      "status": "Trình ký",
      "updatedAt": "2026-04-05",
      "assignedTo": "Kế toán dự án",
      "notes": "Đang hối thúc khách sạn ở Cai Lậy hoàn thiện hóa đơn"
    },
    {
      "id": "doc-4",
      "code": "HS-XE-01",
      "name": "Hồ sơ pháp lý mua 02 xe máy hiện trường",
      "expenseId": "exp-3",
      "category": "Khác",
      "status": "Soạn thảo",
      "updatedAt": "2026-03-25",
      "assignedTo": "Hành chính nhân sự (HCNS)",
      "notes": "Chưa nhận được giấy đăng ký xe từ đơn vị bán"
    }
  ],
  "materials": [
    {
      "id": "mat-1",
      "code": "DẦU-DO",
      "name": "Dầu Diesel 0.05S-II",
      "unit": "Lít",
      "minStock": 500,
      "description": "Dầu phục vụ máy đào, máy phát điện, lu rung hiện trường"
    },
    {
      "id": "mat-2",
      "code": "XM-PCB40",
      "name": "Xi măng PCB40 Hà Tiên",
      "unit": "Bao (50kg)",
      "minStock": 100,
      "description": "Phục vụ đúc dầm và các hạng mục phụ trợ"
    },
    {
      "id": "mat-3",
      "code": "THÉP-D16",
      "name": "Thép thanh vằn Hòa Phát D16",
      "unit": "Tấn",
      "minStock": 2,
      "description": "Cốt thép gia cường sàn dầm"
    },
    {
      "id": "mat-4",
      "code": "NÓN-BHLĐ",
      "name": "Nón bảo hộ lao động Thùy Dương",
      "unit": "Cái",
      "minStock": 20,
      "description": "Nón nhựa trang bị cho kỹ sư và công nhân"
    }
  ],
  "inventoryTransactions": [
    {
      "id": "tx-1",
      "materialId": "mat-1",
      "type": "NHẬP",
      "date": "2026-03-21",
      "quantity": 100,
      "unitPrice": 33420,
      "totalPrice": 3342000,
      "reference": "PN-01/DAU",
      "person": "Đào Văn Phú (Thủ kho)",
      "notes": "Nhập kho dầu trạm chính dầm từ hóa đơn 18109",
      "createdAt": "2026-03-21T11:00:00.000Z"
    },
    {
      "id": "tx-2",
      "materialId": "mat-1",
      "type": "XUẤT",
      "date": "2026-03-24",
      "quantity": 50,
      "unitPrice": 33420,
      "totalPrice": 1671000,
      "reference": "PX-01/DAU",
      "person": "Kỹ sư hiện trường (Đội Trưởng)",
      "notes": "Xuất cấp cho máy đào MPD làm việc 2 ca",
      "createdAt": "2026-03-24T14:00:00.000Z"
    },
    {
      "id": "tx-3",
      "materialId": "mat-4",
      "type": "NHẬP",
      "date": "2026-03-25",
      "quantity": 15,
      "unitPrice": 45000,
      "totalPrice": 675000,
      "reference": "PN-02/VPP",
      "person": "Cô Lan (Hành chính)",
      "notes": "Mua nón bảo hộ lao động cho công nhân mới vào",
      "createdAt": "2026-03-25T11:00:00.000Z"
    },
    {
      "id": "tx-4",
      "materialId": "mat-1",
      "type": "NHẬP",
      "date": "2026-04-04",
      "quantity": 200,
      "unitPrice": 35440,
      "totalPrice": 7088000,
      "reference": "PN-03/DAU",
      "person": "Đào Văn Phú (Thủ kho)",
      "notes": "Nhập dầu cấp máy đào nhập trực tiếp",
      "createdAt": "2026-04-04T09:00:00.000Z"
    },
    {
      "id": "tx-5",
      "materialId": "mat-1",
      "type": "XUẤT",
      "date": "2026-04-05",
      "quantity": 120,
      "unitPrice": 35440,
      "totalPrice": 4252800,
      "reference": "PX-02/DAU",
      "person": "Tài xế máy đào 09",
      "notes": "Đổ dầu trực tiếp máy đào 09 và máy 07",
      "createdAt": "2026-04-05T15:30:00.000Z"
    }
  ]
};
